# Generated by Django 5.2.5 on 2026-09-26 11:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_activeclientuser_demouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='client_earnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Client earnings (auto-calculated from completed client tasks, but editable).', max_digits=12, verbose_name='Client earnings'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='demo_earnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Demo earnings (auto-calculated from completed demo tasks, but editable).', max_digits=12, verbose_name='Demo earnings'),
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='carried_demo_earnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Carried demo earnings'),
        ),
    ]
