# Generated by Django 5.2.5 on 2026-09-26 12:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_clientuser_client_earnings_clientuser_demo_earnings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total earnings (auto-calculated, but editable by admin).', max_digits=12, verbose_name='Total earnings'),
        ),
    ]
